language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.6"
services:
  - redis-server
before_script:
  - sh -c "if [ ! -f config.js ]; then cp config.sample.js config.js; fi"
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    - url: https://tinyspeck.dev.slack.com/services/hooks/travis?token=LxdE55485qOUR4qSnpOigrUX
